# AWS SETTINGS
SECRET_KEY = '...'
PUBLIC_KEY = '...'
ASW_REGION = '...'

# SERVER SETTINGS
SERVER_HOST = 'localhost'
SERVER_PORT = '5000'

# TF SERVING SETTINGS
TF_HOST = 'localhost'
TF_PORT = '8500'
MODEL_SPEC_NAME = '...'